### ISSUE TITLE
ESO Client never appears after instantly closing Bethesda.net_Launcher.exe

### ISSUE THREAD

**Issue by AngelusMortiel** [Medallyon/eso-discord-status#35]
Hey @Medallyon,

I'm trying to see if I can capture some kind of evidence about what is happening here exactly on a technical level, but to explain the layman's observation on what I see happening:

1. Launch Discord
2. Launch ESO DRP client (set to auto-close ESO launcher and auto-close itself when ESO closes)
3. Launch ESO "launcher" (via Steam)
4. Click 'Play" in launcher.
5. ESO does not appear to launch. Checking task manager shows ESO has launched but is "Suspended" in WIndows. DRP client is still running.
6. Taskkill ESO and DRP client closes (as expected).

This does not happen under two conditions:
- If the "auto-close launcher" option is disabled.
- If the DRP client is not opened at all.

My theory here is that the function that kills the ESO launcher may need to simply have a delay added after the game is launched. I don't know C# very well specifically and don't know the inner workings of ESO, but I do know from my experience PowerShell scripting that sometimes adding a pause is needed to give time for a "launcher" application to pass an authentication/license token of some kind into the application proper before killing the launcher (e.g. verifying game is "authentic"). It could be that my system is possibly a bit slow and the DRP client kills the launcher before the ESO application received a "token" from the launcher. Thus, the ESO application suspends itself indefinitely, awaiting that "token" from the now-closed launcher.

```cs
<!--StartFragment-->
if (this.EsoIsRunning)
{
    this.EsoRanOnce = true;
    if ((bool)this.Settings.Get("CloseLauncher"))
    {
        processes = Process.GetProcessesByName("Bethesda.net_Launcher");
        if (processes.Length &gt; 0)
     <!--Insert a "Thread.Sleep()" or "Task.Delay()" here?-->
        processes[0].Kill();
    }
<!--EndFragment-->
```

Thoughts?

**Comment by Medallyon** [comment]
Seems very plausible from your investigation. If you have the time, you could try contributing a fix for this. Otherwise, it may take a while for me to get around to this.

**Comment by AngelusMortiel** [comment]
@Medallyon I'm getting around to playing with this, although I'm not well-versed on C#... As I mentioned before, my experience comes from PowerShell (very different, but with similar elements).

The change I'll be testing looks like this:
```cs
<!--StartFragment-->
if (this.EsoIsRunning)
{
    this.EsoRanOnce = true;

    if ((bool)this.Settings.Get("CloseLauncher"))
    {
        processes = Process.GetProcessesByName("Bethesda.net_Launcher");
        if (processes.Length > 0)
        {
            <!--Adding Thread.Sleep() method here-->
            Thread.Sleep(10000);
            processes[0].Kill();
        }
    }

    if (!this.JustMinimized)
    {
        this.JustMinimized = true;
        this.Minimize();
    }

    this.UpdateStatusField("ESO is running!\nYour status is being updated.", Color.LimeGreen);
}
<!--EndFragment-->
```

**Comment by Medallyon** [comment]
Let me know if the [newest release](https://github.com/Medallyon/eso-discord-rich-presence-client/releases/tag/0.4.4) fixes this behaviour for you!

**Comment by AngelusMortiel** [comment]
@Medallyon So, yes, the recent update appears to have fixed the issue. I was able to run it once and it worked.

Unfortunately, since then, attempting to run the client is returning an unhandled exception error. Unrelated to this particular bug report.
